### ISSUE TITLE
Doesn't seem to be working with Civi 5.65.x ?

### ISSUE THREAD

**Issue by Upperholme** [Skvare/eventbuttonlabel#1]
I have installed this extension with Civi 5.65.2 and I see no custom group or custom fields being created, and no visibility of any config options on the online registration tab of event set-up pages. 

Any plans to have this extension work with recent releases?

**Comment by sunilpawar** [comment]
Thanks @Upperholme for reporting this issue, give us 2-3 days to findout issue and fix it.

**Comment by sunilpawar** [comment]
@Upperholme i tried on CiviCRM `5.66.2` version. it does load Custom fields  for Buttons.
<img width="996" alt="Screenshot 2023-10-31 at 5 32 55 PM" src="https://github.com/Skvare/eventbuttonlabel/assets/377735/f0164517-044c-40ce-bc80-cee1ea02add6">
