### ISSUE TITLE
Error on 5.75.2

### ISSUE THREAD

**Issue by dev-allinappli** [Skvare/eventbuttonlabel#3]
After upgrading to 5.75.2 creating a new event with extension activated throws an error:
`Unable to load template 'file:CRM/Eventbuttonlabel/ButtonFile.tpl`

I've already encountered this issue and it seems to be related to Smarty.

**Comment by sunilpawar** [comment]
I have created new tag, check new tag here https://github.com/Skvare/eventbuttonlabel/tags

**Comment by dev-allinappli** [comment]
thanks a lot! that fixed the issue.
